spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bai2
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
secret-key:
  jwt: XMyyBWViFU04O3xqALP0feZM17p0K8GD2akEgM8wHfs=
  is-base64: true
  expiration-ms: 3600000


